services:
  - type: web
    name: tweakeragent
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn characters.test:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
